### ISSUE TITLE
is this your app id?

### ISSUE THREAD

**Issue by cahlan** [kpfein/weatherish#2]
https://github.com/kpfein/weatherish/blob/master/js/weatherService.js#L4

Where do you get this key from? Is this something you don't want others to see?

**Comment by kpfein** [comment]
Yes, that is my key given by the api I used. I get like 1000 calls/day with it so I wasn't too concerned about it. How would you go about hiding it?

**Comment by cahlan** [comment]
interesting problem. if it's on github, anyone could scrape it and use it. We'd probably want to do something like put it behind a node endpoint so the angular app has to make a call to find out what its app id is. That way it's not embedded automatically in the front end code.
